# Multivariate Analysis

## Discriminant Analysis

In [1]:
#importing the required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#step1: loading the dataset
financial_df = pd.read_csv('/content/financial dataset.csv', index_col=0)

In [3]:
#step2: prevewing the dataset
financial_df.head()

country  year  ...              Level of Educuation                Type of Job
0   Kenya  2018  ...              Secondary education              Self employed
1   Kenya  2018  ...              No formal education       Government Dependent
2   Kenya  2018  ...  Vocational/Specialised training              Self employed
3   Kenya  2018  ...                Primary education  Formally employed Private
4   Kenya  2018  ...                Primary education        Informally employed

[5 rows x 13 columns]

In [4]:
financial_df.shape

(23340, 13)

In [5]:
#step3: preprocessing
X = financial_df.iloc[:, [3,6,7,8]]
y = financial_df.iloc[:, [0]]

In [6]:
X.head()

Has a Bank account  household_size  Respondent Age  gender_of_respondent
0                   1             3.0            24.0                     0
1                   0             5.0            70.0                     0
2                   1             5.0            26.0                     1
3                   0             5.0            34.0                     0
4                   0             8.0            26.0                     1

In [7]:
y.head()

country
0   Kenya
1   Kenya
2   Kenya
3   Kenya
4   Kenya

In [8]:
#step4: Splitting the data set into training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
# Step 5: Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Step 6: Peforming LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=1)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
# Step 7: Training and Making Predictions
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


In [12]:
# Step 8: Evaluating the Performance
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' + str(accuracy_score(y_test, y_pred)))

[[   0  913  301    0]
 [   0 1551  225    0]
 [   0  301  972    0]
 [   0  325   80    0]]
Accuracy0.5404884318766067
