# Multivariate Analysis

## Principal Component Analysis

In [26]:
# Step 1: Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

financial_df = pd.read_csv('/content/financial dataset.csv', index_col=0)

In [27]:
# Step 2: Let's take a look at what our dataset looks like:
financial_df.head()

country  year  ...              Level of Educuation                Type of Job
0   Kenya  2018  ...              Secondary education              Self employed
1   Kenya  2018  ...              No formal education       Government Dependent
2   Kenya  2018  ...  Vocational/Specialised training              Self employed
3   Kenya  2018  ...                Primary education  Formally employed Private
4   Kenya  2018  ...                Primary education        Informally employed

[5 rows x 13 columns]

In [28]:
financial_df.shape

(23340, 13)

In [29]:
financial_df.isnull().sum()

country                   0
year                      0
uniqueid                  0
Has a Bank account        0
Type of Location          0
Cell Phone Access         0
household_size            0
Respondent Age            0
gender_of_respondent      0
The relathip with head    0
marital_status            0
Level of Educuation       0
Type of Job               0
dtype: int64

In [30]:
# Step 3: Preprocessing
X = financial_df.iloc[:, [3,6,7,8]]
Y = financial_df.iloc[:, [0]]

In [31]:
X.head()

Has a Bank account  household_size  Respondent Age  gender_of_respondent
0                   1             3.0            24.0                     0
1                   0             5.0            70.0                     0
2                   1             5.0            26.0                     1
3                   0             5.0            34.0                     0
4                   0             8.0            26.0                     1

In [32]:
Y.head()

country
0   Kenya
1   Kenya
2   Kenya
3   Kenya
4   Kenya

In [33]:
# Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2, random_state=0)


In [34]:
# Step 5: Normalization
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
x_test = sc.transform(X_test)


In [14]:
# Step 6: Applying PCA
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


In [15]:
# Step 7: Explained Variance Ratio
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.28637495, 0.27362671, 0.22324838, 0.21674996])

In [36]:
# Step 8: Using 1 Principal Component
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [37]:
# Step 9: Training and Making Predictions
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, Y_train)
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


In [38]:
# Step 10: Performance Evaluation
# 
from sklearn.metrics import confusion_matrix,accuracy_score


cm = confusion_matrix(Y_test, y_pred)
print(cm)
print('Accuracy' , accuracy_score(Y_test, y_pred))

[[   0    0 1214    0]
 [   0    0 1776    0]
 [   0    0 1273    0]
 [   0    0  405    0]]
Accuracy 0.2727077977720651
